music/urls.py
from django.conf.urls import url
from .import views

app_name = 'music'

urlpatterns = [
	#This should direct to the music home/index
	url(r'^$', views.index, name='index'),

	#This one is for detail => /music/231
	url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

	#This one is for detail => /music/231/favourite
	url(r'^(?P<album_id>[0-9]+)/favourite/$', views.detail, name='favourite')
]

webApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models

# Create your models here.

class Album(models.Model):
	artist = models.CharField(max_length=100)
	album_title = models.CharField(max_length=100)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=100)

	def __str__(self):
		return self.album_title


class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=100)
	is_favourited = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Album
# from django.template import loader
from django.shortcuts import render
from django.http import Http404

# Create your views here.

def index(request):
	albums = Album.objects.all()
	context = {
		'albums' : albums
	}

	return render(request, 'music/index.html', context)

def detail(request, album_id):

	# try :
	# 	album = Album.objects.get(id=album_id)
	# except Album.DoesNotExist:
	# 	raise Http404('Sorry that doesnot exist')	

	album = get_object_or_404(Album, id = album_id)

	return render(request, 'music/detail.html', { 'album' : album });
	# return HttpResponse('<h2>Details for an album' + str(album_id) + '</h2>')

music/templates/music/detail.html
<img src='{{ album.album_logo }}'>
<br>
<h2>Album : {{ album }}</h2>
<h3>Artist : {{ album.artist }}</h3>

<i>Genre: {{ album.genre }}</i>
<br>
<h4><u>Songs</u></h4>


<ul>
	{% for song in album.song_set.all %}
		<li>{{ song.song_title }}</li>
	{% endfor %}
</ul>

music/templates/music/index.html
{% if albums%}
	<h3>All Albums</h3>
	<ul>
		{% for album in albums%}
			<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</li></a>
		{% endfor %}	
	</ul>
{% else %}
	<h3>No Albums Found!</h3>

{% endif %}